### ISSUE TITLE
Load failure: tmp.funda.photon.light undefined

### ISSUE THREAD

**Issue by ShaBren** [aarextiaokhiao/NG-plus-3#25]
Hey there! I'm on the beta/dev branch, and I did a reload this morning shortly (~10h) after my first fundament. However, loading fails because `tmp.funda.photon.light` is undefined, and is being referenced in two places:

`mods/ngp3/fundament/lab.js:L5`
`mods/ngp3/core.js:L401`

I worked around it locally by just commenting out those lines, but I'm not familiar enough with the codebase to fix it :)

Attached is the save that fails to load.
[NG+3 v2.31 Beta - Sun, 17 Mar 2024 11_38_44 GMT.txt](https://github.com/aarextiaokhiao/NG-plus-3/files/14627707/NG%2B3.v2.31.Beta.-.Sun.17.Mar.2024.11_38_44.GMT.txt)

**Comment by aarextiaokhiao** [comment]
Resolved in 3/22/24 build.
