### ISSUE TITLE
[The End]fimidian Breakdown=(

### ISSUE THREAD

**Issue by david19728** [aarextiaokhiao/NG-plus-3#7]
@aarextiaokhiao 
***AD:THE REALITY UPDATE IS ENDING!!!***
***CAN YOU MAKE A MOD FOR THAT???***

**Comment by david19728** [comment]
@aarextiaokhiao 
![END](https://github.com/aarextiaokhiao/NG-plus-3/assets/118419920/deaa66c4-462a-473c-866b-f90dd44d53ee)

**Comment by aarextiaokhiao** [comment]
The open-source version is released. And unfortunately, it is way different. I'll not make a mod on Reality due to being built on Node, Typescript, and Vue.

**Comment by david19728** [comment]
@aarextiaokhiao 
Bonus:What does ***"The Endfimidian Breakdown"***mean?
